name: flutter_mediapipe_vision_platform_interface
description: A minimal wrapper for the pose landmark detector
repository: https://github.com/alexeyinkin/flutter-mediapipe
version: 0.1.1
resolution: workspace

environment:
  sdk: ^3.8.0
  flutter: ^3.35.0

dependencies:
  flutter: { sdk: flutter }
  plugin_platform_interface: ^2.1.8

flutter:
  assets:
    - assets/models/pose_landmarker_lite.task
